# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c44d5cc2551cea35e825770c0f0631163c7b414f7b62afd158f82f10c55e2952836cd914cc443034b7cc0ed1f0cd6cd2465f564cc34bf9da7a0eacf8820a755

test:
  secret_key_base: 15cddb212301d118dc4d39ebb7be4181af6cddebe60aaabf2a23c340207e50d3cc30647b08a6616b803db7aa5baa6f5037a845ce1620240165e8794f7c7d5da2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
